package com.netcracker.edu.project.dao.impl;

/**
 * Created by Alexander on 14.06.2017.
 */
interface SQLRequests {
    String SELECT_OBJTYPE_BY_NAME = "SELECT O.OBJECT_TYPE_ID FROM OBJTYPE O WHERE O.NAME = ?";
    String SELECT_PARENTYPEID_BY_OBJTYPEID = "SELECT O.PARENT_ID FROM OBJTYPE O WHERE O.OBJECT_TYPE_ID = ?";
    String SELECT_ATTRTYPEID_VALUE_BY_OBJTYPEID = "SELECT ATTRTYPE_ID FROM ATTRTYPE WHERE OBJECT_TYPE_ID = ? AND OBJECT_TYPE_ID_REF IS NULL";
    String SELECT_ATTRTYPEID_SINGLEREF_BY_OBJTYPEID = "SELECT ATTRTYPE_ID FROM ATTRTYPE WHERE OBJECT_TYPE_ID = ? AND OBJECT_TYPE_ID_REF IS NOT NULL AND IS_MULTIPLE = 0";
    String SELECT_ATTRTYPEID_MULTLEREF_BY_OBJTYPEID = "SELECT ATTRTYPE_ID FROM ATTRTYPE WHERE OBJECT_TYPE_ID = ? AND OBJECT_TYPE_ID_REF IS NOT NULL AND IS_MULTIPLE = 1";

    String SELECT_PARENTID_BY_OBJECTID = "SELECT O.PARENT_ID FROM OBJECTS O WHERE O.OBJECT_ID = ?";
    String SELECT_VALUE_BY_OBJECTID = "SELECT A.VALUE " +
            "FROM OBJECTS O INNER JOIN ATTRTYPE AT ON (O.OBJECT_ID = ? AND O.OBJECT_TYPE_ID = AT.OBJECT_TYPE_ID) " +
            "  LEFT JOIN ATTRIBUTES A ON (O.OBJECT_ID = A.OBJECT_ID AND AT.ATTRTYPE_ID = A.ATTR_ID) " +
            "WHERE AT.OBJECT_TYPE_ID_REF IS NULL " +
            "ORDER BY AT.ATTRTYPE_ID";
    String SELECT_SINGLE_REFERENCE_BY_OBJID_REQUEST = "SELECT OREF.REFERENCE " +
            "FROM OBJECTS O INNER JOIN ATTRTYPE AT ON (O.OBJECT_ID = ? AND O.OBJECT_TYPE_ID = AT.OBJECT_TYPE_ID) " +
            "  LEFT JOIN OBJREFERENCE OREF ON (O.OBJECT_ID = OREF.OBJECT_ID AND AT.ATTRTYPE_ID = OREF.ATTR_ID) " +
            "WHERE AT.OBJECT_TYPE_ID_REF IS NOT NULL AND AT.IS_MULTIPLE = 0" +
            "ORDER BY AT.ATTRTYPE_ID";
    String SELECT_MULT_REFERENCE_BY_OBJID_REQUEST = "SELECT AT.ATTRTYPE_ID, OREF.REFERENCE " +
            "FROM OBJECTS O INNER JOIN ATTRTYPE AT ON (O.OBJECT_ID = ? AND O.OBJECT_TYPE_ID = AT.OBJECT_TYPE_ID) " +
            "  LEFT JOIN OBJREFERENCE OREF ON (O.OBJECT_ID = OREF.OBJECT_ID AND AT.ATTRTYPE_ID = OREF.ATTR_ID) " +
            "WHERE AT.OBJECT_TYPE_ID_REF IS NOT NULL AND AT.IS_MULTIPLE = 1" +
            "ORDER BY AT.ATTRTYPE_ID";

    String SELECT_OBJID_BY_OBJTYPEID_REQUEST = "SELECT OBJECT_ID FROM OBJECTS WHERE OBJECT_TYPE_ID = ?";

    String INSERT_OBJECT_REQUEST = "INSERT INTO OBJECTS (OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME) VALUES (?, ?, ?, ?)";
    String INSERT_ATTRIBUTE_REQUEST = "INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE) VALUES (?, ?, ?)";
    String INSERT_OBJREF_REQUEST = "INSERT INTO OBJREFERENCE (ATTR_ID, REFERENCE, OBJECT_ID) VALUES (?, ?, ?)";

    String UPDATE_OBJECTS = "UPDATE OBJECTS SET PARENT_ID = ?, NAME = ? WHERE OBJECT_TYPE_ID = ? AND OBJECT_ID = ?";
    String UPDATE_ATTRIBUTES = "UPDATE ATTRIBUTES SET VALUE = ? WHERE OBJECT_ID = ? AND ATTR_ID = ?";
    String UPDATE_OBJREFERENCE = "UPDATE OBJREFERERENCE SET REFERENCE = ? WHERE OBJECT_ID = ? AND ATTR_ID = ?";

    String DELETE_OBJ_BY_OBJID_REQUEST = "DELETE FROM OBJECTS WHERE OBJECT_ID = ?";
    String DELETE_OBJREF_BY_ATTRID_OBJID_REQUEST = "DELETE FROM OBJREFERENCE WHERE ATTR_ID = ? AND OBJECT_ID = ?";

    String NEW_OBJECT_ID = "SELECT OBJECT_ID_SEQ.NEXTVAL FROM DUAL";
}
